"""
MQL5 EA Generator — Ichimoku Rule-based Strategy.
===================================================
Đọc models/top3_configs.json → generate IchiRule_Top{N}.mq5

Mỗi EA gồm:
- Ichimoku cloud break + optional TK cross
- EMA filter (optional)
- SL/TP cố định + optional trailing stop
- Money management: fixed lot, max DD guard
- Commentary chi tiết (entry reason, expected metrics)
"""

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = PROJECT_ROOT / "mql5_output"
CONFIG_PATH = PROJECT_ROOT / "models" / "top3_configs.json"


MQL5_TEMPLATE = '''//+------------------------------------------------------------------+
//| {ea_name}.mq5                                                    |
//| Ichimoku Rule-based EA — Auto-generated by Python optimizer     |
//| Config: ${initial_balance} / Leverage {leverage}x / Lot {lot_size}|
//|                                                                  |
//| TRAIN DATA: Q4 2025 (Oct-Nov-Dec)                               |
//| STRATEGY:   Ichimoku Cloud Break{tk_note}{ema_note}             |
//|                                                                  |
//| TRAIN METRICS:                                                   |
//|   Net Profit  : ${net_profit}                                    |
//|   Return      : {return_pct}%                                   |
//|   Profit Factor: {profit_factor}                                 |
//|   Win Rate    : {win_rate}%                                     |
//|   Max DD      : {max_dd_pct}%                                   |
//|                                                                  |
//| MULTI-MONTH (avg):                                               |
//|   Avg Return/month : {avg_monthly_return}%                       |
//|   Win months       : {win_months}/{total_months}                 |
//|   Avg Max DD       : {avg_max_dd}%                               |
//|   Cháy tài khoản   : {blow_up_months}                           |
//|                                                                  |
//| Source: hungpixi/xauusd-ichimoku-rl-bot                        |
//| Author: Phạm Phú Nguyễn Hưng | comarai.com                     |
//+------------------------------------------------------------------+
#property copyright "Phạm Phú Nguyễn Hưng — comarai.com"
#property link      "https://github.com/hungpixi/xauusd-ichimoku-rl-bot"
#property version   "1.00"
#property description "Ichimoku Cloud Break EA — Auto-generated from Python optimizer"

#include <Trade\\Trade.mqh>
CTrade trade;

//--- Input Parameters
input group "=== ICHIMOKU ==="
input int    InpTenkan  = 9;     // Tenkan-sen period
input int    InpKijun   = 26;    // Kijun-sen period
input int    InpSenkou  = 52;    // Senkou Span B period

input group "=== ENTRY SIGNALS ==="
input bool   InpUseTKCross     = {use_tk_cross};   // Use Tenkan/Kijun cross
input bool   InpUseCloudBreak  = true;              // Use Cloud Break (primary)
input bool   InpRequireCloud   = true;              // Require matching cloud color

input group "=== EMA FILTER ==="
input bool   InpUseEMA    = {use_ema_filter};  // Enable EMA trend filter
input int    InpEMAFast   = 34;                // EMA fast period
input int    InpEMASlow   = 89;                // EMA slow period

input group "=== RISK MANAGEMENT ==="
input double InpLotSize        = {lot_size};   // Lot size
input double InpStopLoss       = {stop_loss};  // Stop Loss ($ from entry)
input double InpTakeProfit     = {take_profit}; // Take Profit ($ from entry)
input bool   InpUseTrailing    = {use_trailing}; // Enable trailing stop
input double InpTrailingStart  = {trailing_start}; // Start trailing at $ profit
input double InpTrailingStep   = {trailing_step};  // Trailing step size $
input int    InpCooldownBars   = {cooldown_bars};  // Bars to wait after close
input int    InpMaxTradesDay   = 10;           // Max trades per day

input group "=== MONEY MANAGEMENT ==="
input double InpMaxDDPercent   = 20.0;        // Max total DD% before stop trading
input double InpInitialBalance = {initial_balance}; // Reference initial balance

//--- Global variables
int h_ichi, h_ema_fast, h_ema_slow;
datetime last_close_time = 0;
int daily_trade_count = 0;
datetime current_day = 0;
double initial_equity;

//+------------------------------------------------------------------+
//| Expert initialization                                            |
//+------------------------------------------------------------------+
int OnInit()
{{
   // Ichimoku indicator
   h_ichi = iCustom(_Symbol, PERIOD_M5, "Examples\\\\Ichimoku",
                    InpTenkan, InpKijun, InpSenkou);
   if(h_ichi == INVALID_HANDLE)
   {{
      Print("❌ Cannot create Ichimoku indicator");
      return INIT_FAILED;
   }}

   // EMA indicators
   if(InpUseEMA)
   {{
      h_ema_fast = iMA(_Symbol, PERIOD_M5, InpEMAFast, 0, MODE_EMA, PRICE_CLOSE);
      h_ema_slow = iMA(_Symbol, PERIOD_M5, InpEMASlow, 0, MODE_EMA, PRICE_CLOSE);
      if(h_ema_fast == INVALID_HANDLE || h_ema_slow == INVALID_HANDLE)
      {{
         Print("❌ Cannot create EMA indicators");
         return INIT_FAILED;
      }}
   }}

   initial_equity = AccountInfoDouble(ACCOUNT_EQUITY);
   trade.SetExpertMagicNumber(202503{rank:02d});
   trade.SetDeviationInPoints(10);

   Print("✅ IchiRule_Top{rank} initialized. Magic: 202503{rank:02d}");
   Print("   SL=$", InpStopLoss, " TP=$", InpTakeProfit,
         " Trailing=", InpUseTrailing, " Lot=", InpLotSize);
   return INIT_SUCCEEDED;
}}

//+------------------------------------------------------------------+
//| Expert deinitialization                                          |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
   IndicatorRelease(h_ichi);
   if(InpUseEMA) {{ IndicatorRelease(h_ema_fast); IndicatorRelease(h_ema_slow); }}
}}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{{
   // Only run on new M5 bar open
   if(!IsNewBar(PERIOD_M5)) return;

   // Max DD guard
   double current_equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double dd_pct = (initial_equity - current_equity) / initial_equity * 100;
   if(dd_pct >= InpMaxDDPercent)
   {{
      static bool dd_warned = false;
      if(!dd_warned)
      {{
         Print("⛔ Max DD reached (", dd_pct, "%). Stopping trading.");
         dd_warned = true;
      }}
      return;
   }}

   // Daily trade counter reset
   MqlDateTime cur_dt;
   TimeToStruct(TimeCurrent(), cur_dt);
   string cur_day_str = IntegerToString(cur_dt.year) + IntegerToString(cur_dt.mon) + IntegerToString(cur_dt.day);
   static string last_day = "";
   if(cur_day_str != last_day)
   {{
      daily_trade_count = 0;
      last_day = cur_day_str;
   }}

   // Cooldown check
   int bars_since_close = 0;
   if(last_close_time > 0)
   {{
      bars_since_close = (int)((TimeCurrent() - last_close_time) / PeriodSeconds(PERIOD_M5));
   }}
   else bars_since_close = 9999;

   // Get indicator values (current and previous bar)
   double tenkan[], kijun[], spanA[], spanB[];
   double ema_f[], ema_s[];
   ArraySetAsSeries(tenkan, true); ArraySetAsSeries(kijun, true);
   ArraySetAsSeries(spanA, true);  ArraySetAsSeries(spanB, true);

   // Ichimoku buffer indices: 0=Tenkan, 1=Kijun, 2=SpanA, 3=SpanB, 4=Chikou
   if(CopyBuffer(h_ichi, 0, 0, 3, tenkan) < 3) return;
   if(CopyBuffer(h_ichi, 1, 0, 3, kijun)  < 3) return;
   if(CopyBuffer(h_ichi, 2, 0, 3, spanA)  < 3) return;
   if(CopyBuffer(h_ichi, 3, 0, 3, spanB)  < 3) return;

   double cloud_top_curr = MathMax(spanA[0], spanB[0]);
   double cloud_bot_curr = MathMin(spanA[0], spanB[0]);
   double cloud_top_prev = MathMax(spanA[1], spanB[1]);
   double cloud_bot_prev = MathMin(spanA[1], spanB[1]);

   double close_curr = iClose(_Symbol, PERIOD_M5, 0);
   double close_prev = iClose(_Symbol, PERIOD_M5, 1);

   // EMA
   bool ema_bull = true, ema_bear = true;
   if(InpUseEMA)
   {{
      ArraySetAsSeries(ema_f, true); ArraySetAsSeries(ema_s, true);
      if(CopyBuffer(h_ema_fast, 0, 0, 2, ema_f) < 2) return;
      if(CopyBuffer(h_ema_slow, 0, 0, 2, ema_s) < 2) return;
      ema_bull = (ema_f[0] > ema_s[0]);
      ema_bear = (ema_f[0] < ema_s[0]);
   }}

   // === SIGNALS ===
   bool buy_signal = false, sell_signal = false;
   string signal_reason = "";

   // Cloud break Buy: prev close <= cloud_top_prev, curr close > cloud_top_curr
   if(InpUseCloudBreak)
   {{
      if(close_prev <= cloud_top_prev && close_curr > cloud_top_curr)
      {{
         if(!InpRequireCloud || spanA[0] > spanB[0])  // Bullish cloud
         {{
            buy_signal = true;
            signal_reason = "CloudBreak_UP";
         }}
      }}
      if(close_prev >= cloud_bot_prev && close_curr < cloud_bot_curr)
      {{
         if(!InpRequireCloud || spanA[0] < spanB[0])  // Bearish cloud
         {{
            sell_signal = true;
            signal_reason = "CloudBreak_DN";
         }}
      }}
   }}

   // TK Cross
   if(InpUseTKCross && !(buy_signal || sell_signal))
   {{
      if(tenkan[1] <= kijun[1] && tenkan[0] > kijun[0])
      {{ buy_signal = true; signal_reason = "TK_Cross_UP"; }}
      if(tenkan[1] >= kijun[1] && tenkan[0] < kijun[0])
      {{ sell_signal = true; signal_reason = "TK_Cross_DN"; }}
   }}

   // Apply EMA filter
   if(InpUseEMA)
   {{
      if(buy_signal && !ema_bull)  buy_signal = false;
      if(sell_signal && !ema_bear) sell_signal = false;
   }}

   // === MANAGE OPEN POSITION ===
   int total_pos = PositionsTotal();
   bool has_position = false;
   ulong pos_ticket = 0;
   for(int i = 0; i < total_pos; i++)
   {{
      if(PositionGetTicket(i) > 0 && PositionGetInteger(POSITION_MAGIC) == 202503{rank:02d})
      {{
         has_position = true;
         pos_ticket = PositionGetTicket(i);
         break;
      }}
   }}

   // Trailing stop management
   if(has_position && InpUseTrailing)
   {{
      ManageTrailing(pos_ticket);
   }}

   // Signal reverse (close opposite)
   if(has_position)
   {{
      ENUM_POSITION_TYPE pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
      if(pos_type == POSITION_TYPE_BUY && sell_signal)
      {{
         trade.PositionClose(pos_ticket);
         last_close_time = TimeCurrent();
         Print("🔄 Closed LONG on signal reverse (", signal_reason, ")");
         return;
      }}
      if(pos_type == POSITION_TYPE_SELL && buy_signal)
      {{
         trade.PositionClose(pos_ticket);
         last_close_time = TimeCurrent();
         Print("🔄 Closed SHORT on signal reverse (", signal_reason, ")");
         return;
      }}
   }}

   // === OPEN NEW POSITION ===
   if(!has_position && bars_since_close >= InpCooldownBars && daily_trade_count < InpMaxTradesDay)
   {{
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
      // Convert $ SL/TP to price distance
      // XAUUSD: 1 point = $0.01, lot_size=0.05 → 1 point PnL = $0.05*100 = $5... 
      // Actually: PnL = price_move * lot * 100oz. So $X = price_move * lot * 100
      // price_move = X / (lot * 100) = X / 5
      double sl_pts = InpStopLoss / (InpLotSize * 100.0);
      double tp_pts = InpTakeProfit / (InpLotSize * 100.0);

      if(buy_signal)
      {{
         double sl = ask - sl_pts;
         double tp = ask + tp_pts;
         if(trade.Buy(InpLotSize, _Symbol, ask, sl, tp,
                      "IchiRule_Top{rank}|" + signal_reason))
         {{
            daily_trade_count++;
            Print("📈 BUY | Reason: ", signal_reason,
                  " | SL=", sl, " TP=", tp, " Lot=", InpLotSize);
         }}
      }}
      else if(sell_signal)
      {{
         double sl = bid + sl_pts;
         double tp = bid - tp_pts;
         if(trade.Sell(InpLotSize, _Symbol, bid, sl, tp,
                       "IchiRule_Top{rank}|" + signal_reason))
         {{
            daily_trade_count++;
            Print("📉 SELL | Reason: ", signal_reason,
                  " | SL=", sl, " TP=", tp, " Lot=", InpLotSize);
         }}
      }}
   }}
}}

//+------------------------------------------------------------------+
//| Manage trailing stop                                             |
//+------------------------------------------------------------------+
void ManageTrailing(ulong ticket)
{{
   if(!PositionSelectByTicket(ticket)) return;

   double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
   double current_sl = PositionGetDouble(POSITION_SL);
   ENUM_POSITION_TYPE pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);

   double sl_pts = InpStopLoss / (InpLotSize * 100.0);
   double trail_start_pts = InpTrailingStart / (InpLotSize * 100.0);
   double trail_step_pts  = InpTrailingStep  / (InpLotSize * 100.0);

   if(pos_type == POSITION_TYPE_BUY)
   {{
      double profit_pts = bid - open_price;
      if(profit_pts >= trail_start_pts)
      {{
         double new_sl = bid - trail_step_pts;
         if(new_sl > current_sl + trail_step_pts * 0.1)
         {{
            trade.PositionModify(ticket, new_sl, PositionGetDouble(POSITION_TP));
         }}
      }}
   }}
   else if(pos_type == POSITION_TYPE_SELL)
   {{
      double profit_pts = open_price - ask;
      if(profit_pts >= trail_start_pts)
      {{
         double new_sl = ask + trail_step_pts;
         if(new_sl < current_sl - trail_step_pts * 0.1 || current_sl == 0)
         {{
            trade.PositionModify(ticket, new_sl, PositionGetDouble(POSITION_TP));
         }}
      }}
   }}
}}

//+------------------------------------------------------------------+
//| Check if new bar opened                                          |
//+------------------------------------------------------------------+
bool IsNewBar(ENUM_TIMEFRAMES tf)
{{
   static datetime last_bar_time = 0;
   datetime current_bar_time = iTime(_Symbol, tf, 0);
   if(current_bar_time != last_bar_time)
   {{
      last_bar_time = current_bar_time;
      return true;
   }}
   return false;
}}
//+------------------------------------------------------------------+
'''


def generate_ea(cfg: dict, output_dir: Path) -> Path:
    """Generate 1 MQL5 EA file từ config dict."""
    rank = cfg["rank"]
    params = cfg["params"]
    train = cfg["train_metrics"]
    mm = cfg["multi_month"]["summary"]

    ea_name = f"IchiRule_Top{rank}"
    tk_note = " + TK Cross" if params.get("use_tk_cross") else ""
    ema_note = " + EMA Filter" if params.get("use_ema_filter") else ""

    blow_up = mm.get("blow_up_months", [])
    blow_str = ", ".join(blow_up) if blow_up else "None ✅"

    mql5_code = MQL5_TEMPLATE.format(
        ea_name=ea_name,
        rank=rank,
        initial_balance=cfg.get("initial_balance", 500),
        leverage=200,
        lot_size=cfg.get("lot_size", 0.05),
        tk_note=tk_note,
        ema_note=ema_note,
        # Train metrics
        net_profit=train.get("net_profit", 0),
        return_pct=train.get("return_pct", 0),
        profit_factor=train.get("profit_factor", 0),
        win_rate=train.get("win_rate", 0),
        max_dd_pct=train.get("max_dd_pct", 0),
        # Multi-month
        avg_monthly_return=mm.get("avg_monthly_return", 0),
        win_months=mm.get("profitable_months", 0),
        total_months=mm.get("total_months_tested", 0),
        avg_max_dd=mm.get("avg_max_dd", 0),
        blow_up_months=blow_str,
        # Params
        stop_loss=params.get("stop_loss", 5.0),
        take_profit=params.get("take_profit", 3.0),
        use_trailing=str(params.get("use_trailing_stop", True)).lower(),
        trailing_start=params.get("trailing_start", 1.0),
        trailing_step=params.get("trailing_step", 0.5),
        cooldown_bars=params.get("cooldown_bars", 5),
        use_tk_cross=str(params.get("use_tk_cross", False)).lower(),
        use_ema_filter=str(params.get("use_ema_filter", True)).lower(),
    )

    out_path = output_dir / f"{ea_name}.mq5"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(mql5_code)

    print(f"  ✅ Generated: {out_path.name}")
    return out_path


def generate_readme(top3: list, output_dir: Path):
    """Generate README.md tóm tắt 3 EAs."""
    lines = ["# IchiRule MQL5 EAs — Auto-generated\n",
             f"> Source: `hungpixi/xauusd-ichimoku-rl-bot` | Website: comarai.com\n",
             f"\nConfig: **$500 account / 200x leverage / 0.05 lot / XAUUSD M5**\n",
             f"Training: Q4 2025 (Oct-Nov-Dec) | Sort: balance > PF > RF > MaxDD\n\n",
             "## Comparison\n",
             "| EA | Net$/month | Return% | PF | WR | MaxDD | Avg Monthly | Win Months |\n",
             "|---|---|---|---|---|---|---|---|\n"]
    for cfg in top3:
        t = cfg["train_metrics"]
        s = cfg["multi_month"]["summary"]
        lines.append(
            f"| IchiRule_Top{cfg['rank']} | ${t['net_profit']:.2f} | "
            f"{t['return_pct']:.2f}% | {t['profit_factor']:.2f} | "
            f"{t['win_rate']:.1f}% | {t['max_dd_pct']:.2f}% | "
            f"{s['avg_monthly_return']:.2f}% | "
            f"{s['profitable_months']}/{s['total_months_tested']} |\n"
        )
    lines.append("\n## How to use\n")
    lines.append("1. Copy `.mq5` file → MT5 `Experts/` folder\n")
    lines.append("2. MetaEditor → Compile → No errors expected\n")
    lines.append("3. Attach to XAUUSD M5 chart\n")
    lines.append("4. Set account balance to $500, leverage 200x\n")
    lines.append("5. Enable AutoTrading\n\n")
    lines.append("---\n_Generated by `generate_mql5.py` | comarai.com_\n")

    readme_path = output_dir / "README.md"
    with open(readme_path, "w", encoding="utf-8") as f:
        f.writelines(lines)
    print(f"  📄 README: {readme_path}")


def generate_all(top3_configs: list):
    """Generate tất cả EAs + README từ top3 configs list."""
    OUTPUT_DIR.mkdir(exist_ok=True)
    print(f"\n{'='*60}")
    print(f"  🖊️  Generating MQL5 EAs → {OUTPUT_DIR}")
    print(f"{'='*60}")
    for cfg in top3_configs:
        generate_ea(cfg, OUTPUT_DIR)
    generate_readme(top3_configs, OUTPUT_DIR)
    print(f"\n✅ {len(top3_configs)} EAs generated in: {OUTPUT_DIR}/\n")


if __name__ == "__main__":
    # Run standalone: load JSON và generate EAs
    if not CONFIG_PATH.exists():
        print(f"❌ {CONFIG_PATH} not found. Run run_optimizer_500.py first.")
        exit(1)
    with open(CONFIG_PATH, encoding="utf-8") as f:
        top3 = json.load(f)
    generate_all(top3)
