//+------------------------------------------------------------------+
//| IchiRule_Top3.mq5                                                    |
//| Ichimoku Rule-based EA — Auto-generated by Python optimizer     |
//| Config: $500.0 / Leverage 200x / Lot 0.05|
//|                                                                  |
//| TRAIN DATA: Q4 2025 (Oct-Nov-Dec)                               |
//| STRATEGY:   Ichimoku Cloud Break + TK Cross + EMA Filter             |
//|                                                                  |
//| TRAIN METRICS:                                                   |
//|   Net Profit  : $871.35                                    |
//|   Return      : 174.27%                                   |
//|   Profit Factor: 1.0882                                 |
//|   Win Rate    : 47.0%                                     |
//|   Max DD      : 45.304%                                   |
//|                                                                  |
//| MULTI-MONTH (avg):                                               |
//|   Avg Return/month : -21.0%                       |
//|   Win months       : 11/25                 |
//|   Avg Max DD       : 80.29%                               |
//|   Cháy tài khoản   : 2024-01, 2024-04, 2024-08, 2024-09, 2024-12, 2025-03, 2025-09, 2026-01                           |
//|                                                                  |
//| Source: hungpixi/xauusd-ichimoku-rl-bot                        |
//| Author: Phạm Phú Nguyễn Hưng | comarai.com                     |
//+------------------------------------------------------------------+
#property copyright "Phạm Phú Nguyễn Hưng — comarai.com"
#property link      "https://github.com/hungpixi/xauusd-ichimoku-rl-bot"
#property version   "1.00"
#property description "Ichimoku Cloud Break EA — Auto-generated from Python optimizer"

#include <Trade\Trade.mqh>
CTrade trade;

//--- Input Parameters
input group "=== ICHIMOKU ==="
input int    InpTenkan  = 9;     // Tenkan-sen period
input int    InpKijun   = 26;    // Kijun-sen period
input int    InpSenkou  = 52;    // Senkou Span B period

input group "=== ENTRY SIGNALS ==="
input bool   InpUseTKCross     = true;   // Use Tenkan/Kijun cross
input bool   InpUseCloudBreak  = true;              // Use Cloud Break (primary)
input bool   InpRequireCloud   = true;              // Require matching cloud color

input group "=== EMA FILTER ==="
input bool   InpUseEMA    = true;  // Enable EMA trend filter
input int    InpEMAFast   = 34;                // EMA fast period
input int    InpEMASlow   = 89;                // EMA slow period

input group "=== RISK MANAGEMENT ==="
input double InpLotSize        = 0.05;   // Lot size
input double InpStopLoss       = 8.0;  // Stop Loss ($ from entry)
input double InpTakeProfit     = 10.0; // Take Profit ($ from entry)
input bool   InpUseTrailing    = false; // Enable trailing stop
input double InpTrailingStart  = 1.5; // Start trailing at $ profit
input double InpTrailingStep   = 0.5;  // Trailing step size $
input int    InpCooldownBars   = 10;  // Bars to wait after close
input int    InpMaxTradesDay   = 10;           // Max trades per day

input group "=== MONEY MANAGEMENT ==="
input double InpMaxDDPercent   = 20.0;        // Max total DD% before stop trading
input double InpInitialBalance = 500.0; // Reference initial balance

//--- Global variables
int h_ichi, h_ema_fast, h_ema_slow;
datetime last_close_time = 0;
int daily_trade_count = 0;
datetime current_day = 0;
double initial_equity;

//+------------------------------------------------------------------+
//| Expert initialization                                            |
//+------------------------------------------------------------------+
int OnInit()
{
   // Ichimoku indicator
   h_ichi = iCustom(_Symbol, PERIOD_M5, "Examples\\Ichimoku",
                    InpTenkan, InpKijun, InpSenkou);
   if(h_ichi == INVALID_HANDLE)
   {
      Print("❌ Cannot create Ichimoku indicator");
      return INIT_FAILED;
   }

   // EMA indicators
   if(InpUseEMA)
   {
      h_ema_fast = iMA(_Symbol, PERIOD_M5, InpEMAFast, 0, MODE_EMA, PRICE_CLOSE);
      h_ema_slow = iMA(_Symbol, PERIOD_M5, InpEMASlow, 0, MODE_EMA, PRICE_CLOSE);
      if(h_ema_fast == INVALID_HANDLE || h_ema_slow == INVALID_HANDLE)
      {
         Print("❌ Cannot create EMA indicators");
         return INIT_FAILED;
      }
   }

   initial_equity = AccountInfoDouble(ACCOUNT_EQUITY);
   trade.SetExpertMagicNumber(20250303);
   trade.SetDeviationInPoints(10);

   Print("✅ IchiRule_Top3 initialized. Magic: 20250303");
   Print("   SL=$", InpStopLoss, " TP=$", InpTakeProfit,
         " Trailing=", InpUseTrailing, " Lot=", InpLotSize);
   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization                                          |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   IndicatorRelease(h_ichi);
   if(InpUseEMA) { IndicatorRelease(h_ema_fast); IndicatorRelease(h_ema_slow); }
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   // Only run on new M5 bar open
   if(!IsNewBar(PERIOD_M5)) return;

   // Max DD guard
   double current_equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double dd_pct = (initial_equity - current_equity) / initial_equity * 100;
   if(dd_pct >= InpMaxDDPercent)
   {
      static bool dd_warned = false;
      if(!dd_warned)
      {
         Print("⛔ Max DD reached (", dd_pct, "%). Stopping trading.");
         dd_warned = true;
      }
      return;
   }

   // Daily trade counter reset
   MqlDateTime cur_dt;
   TimeToStruct(TimeCurrent(), cur_dt);
   string cur_day_str = IntegerToString(cur_dt.year) + IntegerToString(cur_dt.mon) + IntegerToString(cur_dt.day);
   static string last_day = "";
   if(cur_day_str != last_day)
   {
      daily_trade_count = 0;
      last_day = cur_day_str;
   }

   // Cooldown check
   int bars_since_close = 0;
   if(last_close_time > 0)
   {
      bars_since_close = (int)((TimeCurrent() - last_close_time) / PeriodSeconds(PERIOD_M5));
   }
   else bars_since_close = 9999;

   // Get indicator values (current and previous bar)
   double tenkan[], kijun[], spanA[], spanB[];
   double ema_f[], ema_s[];
   ArraySetAsSeries(tenkan, true); ArraySetAsSeries(kijun, true);
   ArraySetAsSeries(spanA, true);  ArraySetAsSeries(spanB, true);

   // Ichimoku buffer indices: 0=Tenkan, 1=Kijun, 2=SpanA, 3=SpanB, 4=Chikou
   if(CopyBuffer(h_ichi, 0, 0, 3, tenkan) < 3) return;
   if(CopyBuffer(h_ichi, 1, 0, 3, kijun)  < 3) return;
   if(CopyBuffer(h_ichi, 2, 0, 3, spanA)  < 3) return;
   if(CopyBuffer(h_ichi, 3, 0, 3, spanB)  < 3) return;

   double cloud_top_curr = MathMax(spanA[0], spanB[0]);
   double cloud_bot_curr = MathMin(spanA[0], spanB[0]);
   double cloud_top_prev = MathMax(spanA[1], spanB[1]);
   double cloud_bot_prev = MathMin(spanA[1], spanB[1]);

   double close_curr = iClose(_Symbol, PERIOD_M5, 0);
   double close_prev = iClose(_Symbol, PERIOD_M5, 1);

   // EMA
   bool ema_bull = true, ema_bear = true;
   if(InpUseEMA)
   {
      ArraySetAsSeries(ema_f, true); ArraySetAsSeries(ema_s, true);
      if(CopyBuffer(h_ema_fast, 0, 0, 2, ema_f) < 2) return;
      if(CopyBuffer(h_ema_slow, 0, 0, 2, ema_s) < 2) return;
      ema_bull = (ema_f[0] > ema_s[0]);
      ema_bear = (ema_f[0] < ema_s[0]);
   }

   // === SIGNALS ===
   bool buy_signal = false, sell_signal = false;
   string signal_reason = "";

   // Cloud break Buy: prev close <= cloud_top_prev, curr close > cloud_top_curr
   if(InpUseCloudBreak)
   {
      if(close_prev <= cloud_top_prev && close_curr > cloud_top_curr)
      {
         if(!InpRequireCloud || spanA[0] > spanB[0])  // Bullish cloud
         {
            buy_signal = true;
            signal_reason = "CloudBreak_UP";
         }
      }
      if(close_prev >= cloud_bot_prev && close_curr < cloud_bot_curr)
      {
         if(!InpRequireCloud || spanA[0] < spanB[0])  // Bearish cloud
         {
            sell_signal = true;
            signal_reason = "CloudBreak_DN";
         }
      }
   }

   // TK Cross
   if(InpUseTKCross && !(buy_signal || sell_signal))
   {
      if(tenkan[1] <= kijun[1] && tenkan[0] > kijun[0])
      { buy_signal = true; signal_reason = "TK_Cross_UP"; }
      if(tenkan[1] >= kijun[1] && tenkan[0] < kijun[0])
      { sell_signal = true; signal_reason = "TK_Cross_DN"; }
   }

   // Apply EMA filter
   if(InpUseEMA)
   {
      if(buy_signal && !ema_bull)  buy_signal = false;
      if(sell_signal && !ema_bear) sell_signal = false;
   }

   // === MANAGE OPEN POSITION ===
   int total_pos = PositionsTotal();
   bool has_position = false;
   ulong pos_ticket = 0;
   for(int i = 0; i < total_pos; i++)
   {
      if(PositionGetTicket(i) > 0 && PositionGetInteger(POSITION_MAGIC) == 20250303)
      {
         has_position = true;
         pos_ticket = PositionGetTicket(i);
         break;
      }
   }

   // Trailing stop management
   if(has_position && InpUseTrailing)
   {
      ManageTrailing(pos_ticket);
   }

   // Signal reverse (close opposite)
   if(has_position)
   {
      ENUM_POSITION_TYPE pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
      if(pos_type == POSITION_TYPE_BUY && sell_signal)
      {
         trade.PositionClose(pos_ticket);
         last_close_time = TimeCurrent();
         Print("🔄 Closed LONG on signal reverse (", signal_reason, ")");
         return;
      }
      if(pos_type == POSITION_TYPE_SELL && buy_signal)
      {
         trade.PositionClose(pos_ticket);
         last_close_time = TimeCurrent();
         Print("🔄 Closed SHORT on signal reverse (", signal_reason, ")");
         return;
      }
   }

   // === OPEN NEW POSITION ===
   if(!has_position && bars_since_close >= InpCooldownBars && daily_trade_count < InpMaxTradesDay)
   {
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
      // Convert $ SL/TP to price distance
      // XAUUSD: 1 point = $0.01, lot_size=0.05 → 1 point PnL = $0.05*100 = $5... 
      // Actually: PnL = price_move * lot * 100oz. So $X = price_move * lot * 100
      // price_move = X / (lot * 100) = X / 5
      double sl_pts = InpStopLoss / (InpLotSize * 100.0);
      double tp_pts = InpTakeProfit / (InpLotSize * 100.0);

      if(buy_signal)
      {
         double sl = ask - sl_pts;
         double tp = ask + tp_pts;
         if(trade.Buy(InpLotSize, _Symbol, ask, sl, tp,
                      "IchiRule_Top3|" + signal_reason))
         {
            daily_trade_count++;
            Print("📈 BUY | Reason: ", signal_reason,
                  " | SL=", sl, " TP=", tp, " Lot=", InpLotSize);
         }
      }
      else if(sell_signal)
      {
         double sl = bid + sl_pts;
         double tp = bid - tp_pts;
         if(trade.Sell(InpLotSize, _Symbol, bid, sl, tp,
                       "IchiRule_Top3|" + signal_reason))
         {
            daily_trade_count++;
            Print("📉 SELL | Reason: ", signal_reason,
                  " | SL=", sl, " TP=", tp, " Lot=", InpLotSize);
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Manage trailing stop                                             |
//+------------------------------------------------------------------+
void ManageTrailing(ulong ticket)
{
   if(!PositionSelectByTicket(ticket)) return;

   double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
   double current_sl = PositionGetDouble(POSITION_SL);
   ENUM_POSITION_TYPE pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);

   double sl_pts = InpStopLoss / (InpLotSize * 100.0);
   double trail_start_pts = InpTrailingStart / (InpLotSize * 100.0);
   double trail_step_pts  = InpTrailingStep  / (InpLotSize * 100.0);

   if(pos_type == POSITION_TYPE_BUY)
   {
      double profit_pts = bid - open_price;
      if(profit_pts >= trail_start_pts)
      {
         double new_sl = bid - trail_step_pts;
         if(new_sl > current_sl + trail_step_pts * 0.1)
         {
            trade.PositionModify(ticket, new_sl, PositionGetDouble(POSITION_TP));
         }
      }
   }
   else if(pos_type == POSITION_TYPE_SELL)
   {
      double profit_pts = open_price - ask;
      if(profit_pts >= trail_start_pts)
      {
         double new_sl = ask + trail_step_pts;
         if(new_sl < current_sl - trail_step_pts * 0.1 || current_sl == 0)
         {
            trade.PositionModify(ticket, new_sl, PositionGetDouble(POSITION_TP));
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Check if new bar opened                                          |
//+------------------------------------------------------------------+
bool IsNewBar(ENUM_TIMEFRAMES tf)
{
   static datetime last_bar_time = 0;
   datetime current_bar_time = iTime(_Symbol, tf, 0);
   if(current_bar_time != last_bar_time)
   {
      last_bar_time = current_bar_time;
      return true;
   }
   return false;
}
//+------------------------------------------------------------------+
